#!/bin/sh

cd ${0%/*} || exit 1
source /opt/openfoam9/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

cp system/decomposeParDict system/heater/
cp system/decomposeParDict system/metal/
cp system/decomposeParDict system/fluid/

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication splitMeshRegions -cellZones -overwrite
runApplication decomposePar -allRegions
runParallel $(getApplication)
runApplication reconstructPar -allRegions
paraFoam -touchAll
