#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
# May be required to run inside singularity with singularity exec
source /opt/openfoam10/etc/bashrc
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication decomposePar

runParallel $(getApplication)

#------------------------------------------------------------------------------
